language: python
dist: bionic
sudo: false

jobs:
  include:
    - python: 3.6
      env: TOX_ENV=flake8
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8
      env: TOX_ENV=py38
    - python: 3.9
      env: TOX_ENV=py39
    - python: pypy3
      env: TOX_ENV=pypy3

install:
  - travis_retry pip install tox coveralls

script:
  - "tox -e $TOX_ENV -- $TOX_ARGS"

after_success:
  - coveralls

